# Generated by Django 6.0.6 on 2026-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.CharField(max_length=255),
        ),
    ]
