# Generated by Django 6.0.6 on 2026-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_application_cv_alter_application_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
