# Generated by Django 6.0.6 on 2026-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_attendance_check_out_attendance_late_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='marked_at',
            new_name='check_in',
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_today',
            field=models.BooleanField(default=False),
        ),
    ]
