# Generated by Django 6.0.6 on 2026-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='late_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
