# Generated by Django 6.0.6 on 2026-06-12 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_alter_attendance_late_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
