# Generated by Django 6.0.6 on 2026-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_alter_attendance_date_alter_attendance_late_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='was_absent',
            field=models.BooleanField(default=False),
        ),
    ]
