# Generated by Django 6.0.6 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0008_attendance_was_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
