# Generated by Django 6.0.6 on 2026-06-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assined_by',
            new_name='assigned_by',
        ),
    ]
