# Generated by Django 6.0.6 on 2026-06-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_rename_assined_by_task_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='created_at',
        ),
    ]
