# Generated by Django 6.0.6 on 2026-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_rename_created_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='info', max_length=50),
        ),
    ]
